# Generated by Django 4.0.4 on 2022-04-23 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255, verbose_name='Straße')),
                ('house_no', models.CharField(max_length=12, verbose_name='Hausnummer')),
                ('address_extra', models.CharField(max_length=255, verbose_name='Addresszusatz')),
                ('post_code', models.CharField(max_length=25, verbose_name='Postleitzahl')),
                ('town', models.CharField(max_length=255, verbose_name='Stadt')),
                ('country', models.CharField(choices=[('0', 'Deutschland'), ('1', 'Belgien'), ('2', 'Bulgarien'), ('3', 'Dänemark'), ('4', 'Estland'), ('5', 'Finnland'), ('6', 'Frankreich'), ('7', 'Griechenland'), ('8', 'Großbritannien'), ('9', 'Island'), ('10', 'Italien'), ('11', 'Lettland'), ('12', 'Lichtenstein'), ('13', 'Litauen'), ('14', 'Luxemburg'), ('15', 'Niederlande'), ('16', 'Norwegen'), ('17', 'Polen'), ('18', 'Portugal'), ('19', 'Rumänien'), ('20', 'Schweden'), ('21', 'Schweiz'), ('22', 'Slowakei'), ('23', 'Spanien'), ('24', 'Tschechien'), ('25', 'Urkaine'), ('26', 'Ungarn'), ('27', 'Zypern'), ('28', 'Österreich')], default='Deutschland', max_length=25, verbose_name='Land')),
                ('telephone_no', models.CharField(max_length=255, verbose_name='Telefon Nummer')),
                ('default_shipment_address', models.BooleanField(default=False)),
                ('default_billing_address', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
