# Generated by Django 4.0.4 on 2022-04-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_extra',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Addresszusatz'),
        ),
    ]
